
import { ViewState } from './types';

export const VIEW_LABELS: Record<ViewState, string> = {
  'dashboard': 'DASHBOARD',
  'routes': 'ITINERÁRIOS',
  'schedule': 'ESCALA DE VIAGENS',
  'drivers': 'COLABORADORES',
  'companies': 'EMPRESAS',
  'users': 'USUÁRIOS',
  'vehicles': 'FROTA',
  'observations': 'OCORRÊNCIAS',
  'cities': 'CIDADES',
  'notices': 'AVISOS',
  'reports-view': 'RELATÓRIOS',
  'maintenance': 'MANUTENÇÃO',
  'ticketing': 'GUICHÊ DE VENDAS',
  'inspections': 'VISTORIA',
  'ticketing-config': 'CONFIG. VENDAS',
  'time-tracking': 'PONTO ELETRÔNICO',
  'payroll': 'FOLHA DE PAGAMENTO',
  'management': 'GESTÃO GLOBAL',
  'shifts': 'GERENCIAMENTO DE TURNO',
  'notifications': 'ALERTAS E AVISOS',
  'dispatcher': 'DESPACHANTE',
  'sac': 'SAC - IMPCARD',
  'work-with-us': 'TRABALHE CONOSCO',
  'recruitment': 'PAINEL DE RECRUTAMENTO',
  'skins': 'REPOSITÓRIO DE SKINS',
  'about': 'SOBRE O SISTEMA',
  'subscriptions': 'ASSINATURAS',
  'license-management': 'GESTÃO DE LICENÇAS',
  'my-subscription': 'MINHA ASSINATURA',
  'system-config': 'CONFIG. SISTEMA',
  'operation-center': 'CENTRO OPERACIONAL',
  'driver-view': 'ÁREA DO MOTORISTA',
  'passenger-view': 'PORTAL DO PASSAGEIRO',
  'driver-urban': 'MOTORISTA URBANO',
  'driver-road': 'MOTORISTA RODOVIÁRIO',
  'conductor': 'COBRADOR',
  'monitoring': 'MONITORAMENTO',
  'bus-stations': 'RODOVIÁRIAS'
};
